
import type { Metadata } from "next";
import "./globals.css";
import Windows95FrameOuter from "@/components/Windows95FrameOuter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`antialiased bg-red-200 md:bg-yellow-200 lg:bg-green-200 xl:bg-blue-200 2xl:bg-purple-200 m-4 md:m-6 lg:m-8 xl:m-16 2xl:m-24`}>
        
        {children}
        
      </body>
    </html>
  );
}
