
import type { Metadata } from "next";
import "./globals.css";
import Windows95FrameOuter from "@/components/Windows95FrameOuter";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth ">
      <body className={`antialiased bg-purple-200 `}>
          {/* <div className={`bg-red-200 md:bg-yellow-200 lg:bg-green-200 xl:bg-blue-200 2xl:bg-purple-200 `}>
            {children}
          </div> */}
          {children}
          <footer className="p-[1.5rem] md:p-[3rem] lg:p-[4rem] xl:px-[5rem] 2xl:px-[6rem]">
            <div className="pb-[7rem] lg:pb-[0rem]">
              <div className="flex flex-col py-container gap-6 md:gap-8 lg:gap-10 items-center lg:items-start">
                <p className="font-Doto text-[1.15rem] md:text-[1.2rem] lg:text-[1.3rem]">. . .</p>
                <div className="flex flex-col gap-[0.5rem] font-Doto text-center lg:text-left">
                  <p>Hand-coded with 🩷 with React, NextJS, and Tailwind</p>
                  <p>Jinny Seo (c) 2025</p>
                </div>
              </div>
            </div>
          </footer>
      </body>
    </html>
  );
}
